version: '3.8'

#
# TODO upgrade to 2.7.3.Final
#
services:
  zookeeper0:
    image: debezium/zookeeper:2.7
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    image: debezium/kafka:2.7
    depends_on:
      - zookeeper0
    ports:
      - 9092:9092
    restart: unless-stopped
    environment:
      BROKER_ID: 100
      ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  
  # https://debezium.io/documentation/reference/stable/configuration/avro.html#apicurio-registry
  schemaregistry0:
    image: apicurio/apicurio-registry-kafkasql:latest-release
    depends_on:
      - kafka0
    ports:
      - 8085:8080
    restart: unless-stopped
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka0:9092
      REGISTRY_KAFKASQL_CONSUMER_GROUP_ID: apicurio-registry-local

  kafka-connect0:
    image: quay.io/yugabyte/debezium-connector:1.9.5.y.220.2
    depends_on:
      - schemaregistry0
    ports:
      - 8083:8083
    restart: unless-stopped
    environment:
      BOOTSTRAP_SERVERS: kafka0:9092
      GROUP_ID: kafka-connect0-group
      CONFIG_STORAGE_TOPIC: kafka-connect0_configs
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_TOPIC: kafka-connect0_offset
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_TOPIC: kafka-connect0_status
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      REST_ADVERTISED_HOST_NAME: kafka-connect0
      CONNECT_REST_PORT: 8083
      CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE: avro
      ENABLE_APICURIO_CONVERTERS: true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - schemaregistry0
    ports:
      - 8180:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: debezium-local
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper0:2181
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8080/apis/ccompat/v7
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect0
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083

  #
  # https://dev.to/docker/how-to-run-oracle-database-in-a-docker-container-using-docker-compose-1c9b
  # https://debezium.io/blog/2022/09/30/debezium-oracle-series-part-1/
  # https://royalihasan.medium.com/integrating-oracle-database-with-debezium-and-kafka-connect-for-cdc-change-data-capture-f44d758e7f69
  #
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: tiger
  
  yugabytedb:
    image: yugabytedb/yugabyte:2024.1.2.0-b77
    ports: 
      - "7000:7000"   # YB Master (7001:7000 on Monteray)
      - "9000:9000"   # YB TServer
      - "15433:15433" # Yugabyted UI
      - "5433:5433"   # YSQL
      - "9042:9042"   # YCQL
    command: >
      bash -c 'rm -rf /tmp/.yb.* ;
      yugabyted start --background=false --tserver_flags=yb_enable_read_committed_isolation=true'

# TODOs
#
# - add Health Checks to containers
#
# - add Oracle Container volumes so it doesn't take so long to do a full restart
#     volumes:
#       - oracle-data:/opt/oracle/oradata
#       - oracle-backup:/opt/oracle/backup
#
# - add YugabyteDB volume(s)