--
-- Highly simplified "product order" schema to demonstrate multiple tables,
-- relations and data types for data migration from Oracle with Debezium.
--

CREATE TABLE customer (
  customer_id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  date_of_birth DATE,
  full_name     VARCHAR2(150) NOT NULL,
  email         VARCHAR2(100),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_customer PRIMARY KEY (customer_id),
  CONSTRAINT uc_customer_email UNIQUE (email)
);

create table store (
  store_id         INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  banner_name      VARCHAR2(100) NOT NULL,
  web_address      VARCHAR2(100 CHAR),
  physical_address VARCHAR2(512 CHAR),
  postal_code      VARCHAR2(10),
  latitude         NUMBER(9,6),
  longitude        NUMBER(9,6),
  CONSTRAINT pk_store PRIMARY KEY (store_id)
);

CREATE TABLE product (
  product_id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  product_name VARCHAR2(255 CHAR) NOT NULL,
  product_desc VARCHAR2(512 CHAR),
  unit_price   NUMBER(10,2),
  CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE customer_order (
  order_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  store_id     INTEGER NOT NULL,
  customer_id  INTEGER NOT NULL,
  order_status VARCHAR2(10 CHAR) NOT NULL,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_order PRIMARY KEY (order_id),
  CONSTRAINT ck_order_status CHECK (order_status IN ('CANCELLED', 'COMPLETE', 'OPEN', 'PAID', 'REFUNDED', 'SHIPPED')),
  CONSTRAINT fk_store FOREIGN KEY (store_id) REFERENCES store(store_id),
  CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

CREATE TABLE order_item (
  order_id     INTEGER NOT NULL,
  line_item_id INTEGER NOT NULL,
  product_id   INTEGER NOT NULL,
  unit_price   NUMBER(10,2) NOT NULL,
  quantity     INTEGER NOT NULL,
  CONSTRAINT pk_order_item PRIMARY KEY (order_id, line_item_id),
  CONSTRAINT uc_order_item_product UNIQUE (order_id, product_id),
  CONSTRAINT fk_order_item_order_id FOREIGN KEY (order_id) REFERENCES customer_order(order_id) ON DELETE CASCADE,
  CONSTRAINT fk_order_item_product_id FOREIGN KEY (product_id) REFERENCES product(product_id)
);

-- Generated data

INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1985-01-15', 'YYYY-MM-DD'), 'John Doe', 'john.doe@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1990-03-22', 'YYYY-MM-DD'), 'Jane Smith', 'jane.smith@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1982-07-09', 'YYYY-MM-DD'), 'Michael Brown', 'michael.brown@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1975-11-02', 'YYYY-MM-DD'), 'Emily Davis', 'emily.davis@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1995-04-18', 'YYYY-MM-DD'), 'David Wilson', 'david.wilson@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1988-09-14', 'YYYY-MM-DD'), 'Sophia Johnson', 'sophia.johnson@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1992-06-30', 'YYYY-MM-DD'), 'Chris Lee', 'chris.lee@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1987-12-24', 'YYYY-MM-DD'), 'Anna White', 'anna.white@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1983-05-05', 'YYYY-MM-DD'), 'James Clark', 'james.clark@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1991-08-08', 'YYYY-MM-DD'), 'Olivia Martinez', 'olivia.martinez@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1979-10-21', 'YYYY-MM-DD'), 'William Lewis', 'william.lewis@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1984-02-16', 'YYYY-MM-DD'), 'Ava Walker', 'ava.walker@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1980-07-01', 'YYYY-MM-DD'), 'Lucas Hall', 'lucas.hall@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1993-11-05', 'YYYY-MM-DD'), 'Mia Allen', 'mia.allen@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1986-03-17', 'YYYY-MM-DD'), 'Liam Young', 'liam.young@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1994-01-29', 'YYYY-MM-DD'), 'Isabella King', 'isabella.king@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1989-09-11', 'YYYY-MM-DD'), 'Benjamin Scott', 'benjamin.scott@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1978-12-09', 'YYYY-MM-DD'), 'Grace Hill', 'grace.hill@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1996-04-25', 'YYYY-MM-DD'), 'Daniel Adams', 'daniel.adams@example.com');
INSERT INTO customer (date_of_birth, full_name, email) VALUES (TO_DATE('1981-06-20', 'YYYY-MM-DD'), 'Chloe Green', 'chloe.green@example.com');

INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('QuickMart', 'www.quickmart.com', '123 Elm St, Cityville, CA', '90210', 34.0522, -118.2437);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('ShopEasy', 'www.shopeasy.com', '456 Oak Ave, Townburg, TX', '73301', 30.2672, -97.7431);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('GroceryKing', 'www.groceryking.com', '789 Pine St, Lakeview, FL', '33101', 25.7617, -80.1918);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('ElectroWorld', 'www.electroworld.com', '101 Maple Rd, Riverstone, WA', '98001', 47.6062, -122.3321);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('FashionHub', 'www.fashionhub.com', '202 Birch St, Hillside, NY', '10001', 40.7128, -74.0060);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('HomeEssentials', 'www.homeessentials.com', '303 Cedar Ln, Rocktown, CO', '80202', 39.7392, -104.9903);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('PetPalace', 'www.petpalace.com', '404 Palm St, Seaside, FL', '32459', 30.3290, -86.1365);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('BookBarn', 'www.bookbarn.com', '505 Aspen Blvd, Ridgewood, OR', '97201', 45.5051, -122.6750);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('ToyUniverse', 'www.toyuniverse.com', '606 Spruce Ave, Playville, OH', '44101', 41.4993, -81.6944);
INSERT INTO store (banner_name, web_address, physical_address, postal_code, latitude, longitude) VALUES ('GadgetGalaxy', 'www.gadgetgalaxy.com', '707 Redwood Dr, InnovateCity, CA', '94016', 37.7749, -122.4194);

INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Laptop Pro', 'High-end professional laptop with 16GB RAM and 512GB SSD', 1299.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI', 29.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Bluetooth Headphones', 'Over-ear noise-canceling Bluetooth headphones', 199.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Smartphone X', 'Latest smartphone with 128GB storage and 12MP camera', 899.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Gaming Keyboard', 'Mechanical keyboard with customizable RGB lighting', 99.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('4K Monitor', '27-inch 4K monitor with HDR support', 349.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Portable Charger', '10,000mAh portable charger with fast charging support', 39.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Smartwatch Z', 'Fitness tracking smartwatch with GPS and heart-rate monitor', 249.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('External Hard Drive', '1TB USB 3.0 external hard drive', 59.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Wireless Earbuds', 'True wireless earbuds with charging case', 79.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Digital Camera', '24MP mirrorless camera with interchangeable lens', 1199.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Smart TV', '55-inch 4K UHD Smart TV with voice control', 649.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Robot Vacuum', 'Wi-Fi connected robot vacuum cleaner with auto charging', 399.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Electric Kettle', 'Stainless steel electric kettle with temperature control', 49.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Coffee Maker', '12-cup programmable coffee maker with thermal carafe', 99.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Air Purifier', 'HEPA air purifier with 3-speed fan and night mode', 199.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Gaming Console', 'Next-gen gaming console with 1TB storage', 499.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Electric Scooter', 'Foldable electric scooter with a 15-mile range', 299.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Smart Thermostat', 'Wi-Fi smart thermostat with energy-saving features', 129.99);
INSERT INTO product (product_name, product_desc, unit_price) VALUES ('Blender Pro', 'High-speed blender with 1500W motor and multiple presets', 149.99);

INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (1, 1, 'OPEN');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (2, 2, 'PAID');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (3, 3, 'SHIPPED');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (4, 4, 'COMPLETE');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (1, 5, 'REFUNDED');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (2, 6, 'CANCELLED');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (3, 7, 'OPEN');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (4, 8, 'PAID');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (1, 9, 'SHIPPED');
INSERT INTO customer_order (store_id, customer_id, order_status) VALUES (2, 10, 'COMPLETE');

INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (1, 1, 1, 1299.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (1, 2, 2, 29.99, 2);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (2, 1, 3, 199.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (2, 2, 4, 899.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (3, 1, 5, 99.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (3, 2, 6, 349.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (4, 1, 7, 39.99, 3);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (4, 2, 8, 249.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (5, 1, 9, 59.99, 2);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (5, 2, 10, 79.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (6, 1, 11, 1199.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (6, 2, 12, 649.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (7, 1, 13, 399.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (7, 2, 14, 49.99, 2);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (8, 1, 15, 99.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (8, 2, 16, 199.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (9, 1, 17, 499.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (9, 2, 18, 299.99, 2);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (10, 1, 19, 129.99, 1);
INSERT INTO order_item (order_id, line_item_id, product_id, unit_price, quantity) VALUES (10, 2, 20, 149.99, 1);

quit;
/
